Class {
	#name : #TestedClassWithMethod,
	#superclass : #Object,
	#category : #'Migration-Tool-ExternalBrowser'
}

{ #category : #'as yet unclassified' }
TestedClassWithMethod >> methodA [

'example code A'
]

{ #category : #'as yet unclassified' }
TestedClassWithMethod >> methodB [

'example code B'
]

{ #category : #'as yet unclassified' }
TestedClassWithMethod >> methodC [

'example code C'
]

{ #category : #'as yet unclassified' }
TestedClassWithMethod >> methodD [

'example code D'
]
